### ISSUE TITLE
0.2.0 Release todo list

### ISSUE THREAD

**Issue by oleiade** [oleiade/trousseau#36]
- [x] Bump version in constants
- [x] Update changelog (clearly separate new features from fixes and updates
- [x] Push packages to bintray
- [x] Add changelog link into README
- [x] run go fmt
- [x] run go vet
- [ ] Ask buddies to check if they found typos and wrong english statements in the README
- [x] Bump trousseau homebrew formula version
